#数据库连接
spring:
  datasource:
    url: jdbc:mysql:///chapter01
    username: root
    password: TANtao0826
    driver-class-name: com.mysql.cj.jdbc.Driver

#xxl-job，配置文件
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #分别配置执行器的名称、ip地址、端口号
      #注意：如果配置多个执行器时，防止端口冲突
    executor:
      appname: my-xxl-job
      logpath: /data/apps/logs/demo
      ip: 127.0.0.1
      port: 9995
      logretentiondays: 10

server:
  port: 8090