#工程相关
spring:
  profiles:
    active: dev
  application:
    name: springboot4study
# 数据库
  datasource:
    url: jdbc:mysql://150.158.55.44:3306/ssh_data?characterEncoding=utf-8&useSSL=false
    username: sshUser
    password: sshRoot5544
    driver-class-name: com.mysql.cj.jdbc.Driver
# rabbit mq
  rabbitmq:
    host: 150.158.55.44
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
# redis
  redis:
    host: 150.158.55.44
    port: 6379


#xxl-job，配置文件
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #分别配置执行器的名称、ip地址、端口号
      #注意：如果配置多个执行器时，防止端口冲突
    executor:
      appname: my-xxl-job
      logpath: /Users/privatetan/Develop/data/applogs/apps
      ip: 127.0.0.1
      port: 9995
      logretentiondays: 10

server:
  port: 8090

# 引入日志配置文件
logging:
  config: classpath:log4j2.xml

http:
  log-request-details: true



